swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/"

# Paths supported by the server application
paths:
  /callPred/{ride_id}:
    get:
      operationId: "callPred.read"
      tags:
        - "callPred"
      summary: "The prediction data structure supported by the server application"
      description: "Read the list of predictions"
      parameters:
        - name: ride_id
          in: path
          description: ID of the ride to get
          type: string
          required: True
      responses:
        200:
          description: "Successful read prediction operation"
          schema:
            type: "array"
            items:
              properties:
                prediction:
                  type: "object"
  /graph/{ride_id}:
    get:
      operationId: "callPred2.read"
      tags:
        - "callPred2"
      summary: "The prediction data structure supported by the server application"
      description: "Read the list of predictions"
      parameters:
        - name: ride_id
          in: path
          description: ID of the ride to get
          type: string
          required: True
      responses:
        200:
          description: "Successful read prediction operation"
          schema:
            type: "array"
            items:
              properties:
                prediction:
                  type: "object"
